name: Generate Lighthouse Report

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Popular Fonts
        run: |
          npm install -g lighthouse
          lighthouse https://raybo.org/githubchallenge/
