name: Generate Lighthouse Report

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Get Report
        run: |
          npm install -g lighthouse
          lighthouse https://raybo.org/githubchallenge --chrome-flags="--headless" --only-categories accessibility
          
