name: Generate Lighthouse Report

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Report
        run: |
          npm set prefix ~/.npm
          printf "PATH=\"$HOME/.npm/bin:$PATH\"" >> ~/.bashrc
          printf "PATH=\"./node_modules/.bin:$PATH\"" >> ~/.bashrc
          npm install -g lighthouse
          lighthouse https://raybo.org/githubchallenge/
