name: Generate Lighthouse Report

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Get Report
        run: |
          npm install -g accessibility-checker
          achecker ./docs/index.html
